name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.9.1
          
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file app/parent/Dockerfile --tag my-image-name:$(date +%s)
      run: docker build . --file app/appointment/Dockerfile --tag my-image-name:$(date +%s)
