name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: setup Node.js ${{ matrix.node-version }}
      uses: actions/checkout@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: npm init -y
      working-directory: ./app/parent

    - name: Build app
      run: npm install express
      working-directory: ./app/parent
          
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file app/parent/Dockerfile --tag my-image-name:$(date +%s)
